# Generated by Django 4.1.4 on 2022-12-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='weight',
        ),
        migrations.AddField(
            model_name='toy',
            name='age',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toy',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
