# Generated by Django 4.1.4 on 2022-12-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_toy_description_remove_toy_weight_toy_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'verbose_name': 'Игрушка', 'verbose_name_plural': 'Игрушки'},
        ),
        migrations.AlterField(
            model_name='toy',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
